### ISSUE TITLE
potential bugs & theoretical principle request 

### ISSUE THREAD

**Issue by XiaoyuZeng** [cvoeten/permutes#7] opened 2023-07-13 03:40 UTC
Hi,
Thanks for your time and effort to develop this amazing tool for LME+cluster permutation. really appreciate it!
When I applied this tool to my data, however, I encountered some problems that makes me very confusing. I will highly appreciate it if you can help me with this and I hope the answer to this problem could also benefit other users.

## Problem
when this algorithm, the LME+cluster permutation, was applied to two similar datasets, the results were quite different, as you can see from the enclosed figure.
![image](https://github.com/cvoeten/permutes/assets/38243112/b66bb3d0-74df-4f42-9029-4e29151ab51a)
The top figure was the raw regression beta time series that before any multiple comparison correction.
The bottom figure was the one derived from the permutes package. Note that the LME formulas for these two figures were identical. The only difference between these two was whether they went through cluster-based permutation tests.
For the orange regression beta time series, you can see that the lme+cluster-permutation indeed mitigates some smaller clusters.
However, the blue regression beta time series were nearly identical for these two figures, suggesting cluster-permutation did nothing here.
## Attempts to clarify the problem
I'm not convinced by this result. Therefore, I dig into the stats behind the LME+cluster-permutation.
![image](https://github.com/cvoeten/permutes/assets/38243112/01714740-ba8d-46b0-aee2-07b3c5ef5da8)
After looking into the beta, T, cluster_mass, p_cluster_mass values of the orange and blue regression beta time series, I noticed that **for the smaller cluster in the orange time series, the regression betas/t values were actually bigger than that from the blue time series. however, the lme+cluster-permutation mitigated these smaller clusters in the orange time series, but kept the even smaller clusters in the blue time series**...This leads to my questions from the very beginning.

I also checked that the significant clusters using the built-in plot function in the _permutes_. The right panel was significanct clusters for the blue time series, and the left panel was significant clusters for the orange time series.
![image](https://github.com/cvoeten/permutes/assets/38243112/2d6e32ee-fab4-4423-991c-3c87489236fb)

## Specific questions
I got several specific questions:
1: do you think these results were reasonable? or do you have any ideas to debug?
2: could you also clarify the **theoretical principles** behind the lme+cluster-permutation so that 1) users could be more familiar with the algorithm and 2) I can cite it in my paper? I find the 2012 paper you mentioned was actually targeting the random effect, and the comments inside your source code were also hard to understand.

enclosed you can find data and code to replicate this problem.
[PMC_subLME_prepdata.zip](https://github.com/cvoeten/permutes/files/12035068/PMC_subLME_prepdata.zip)
[LAs_lme_sublme_clusterp.zip](https://github.com/cvoeten/permutes/files/12035071/LAs_lme_sublme_clusterp.zip)

Looking forward to your reply! 

Best,
Xiaoyu

**Comment by cvoeten** [comment] 2023-07-13 16:08
This seems to be working as expected. The basic principle behind the approach taken in permutes is the same as permutation testing in general. That is, running hundreds of regression models incurs a
multiple comparison problem; getting your p-values empirically works around that. For mixed-effects models, there is a performance problem (running hundreds of thousands of mixed-effects models in the
naive way will be unacceptably slow), hence why permutes uses the Lee & Braun approach of partialing out everything except the focal term, and then fitting permuted likelihood ratio tests on just the
marginal errors. You've correctly observed that this is a simpler version of the more complex problem of testing random effects, which is the focus of Lee & Braun's paper, but the approach is the
same. As an added feature, permutes keeps track of the permuted LRTs and passes them off to the permuco package to compute cluster-mass tests, if you're interested in *cluster-based* permutations.

All this means that your beta coefficients should, in principle, be exactly the same between a bunch of lmer models and permutes models -- permutes only touches the p-values, not the betas. You've
correctly observed that they're not always exactly the same. The reason for that is that permutes uses buildmer to fit each model, which will remove random effects if they prevent the model from
converging. This seemed preferable than raising an error just because one of possibly hundreds of models did not converge with the user-provided random-effect structure. If random effects are
eliminated, larger betas and t-values and smaller p-values are the natural result.

This seems more like a support question than a bug report, for which Github isn't really the proper venue. Closing.

**Closed** 2023-07-13 16:09 UTC
